name: sure_mobile_app
description: Sure Mobile App - Flutter Clean Architecture Template
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.3

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/localizations/
